services:
  hub:
    image: ${HARBOR}corridor-foundation-service:${HUB_VERSION}
    container_name: sceg-hub
    restart: unless-stopped
    ports:
      - "8090:8090"
    env_file:
      - ./.env.hub
    environment:
      STORAGE_S3_ENDPOINT: http://${HOST_S3_IP:-minio}:9000

  cigs:
    image: ${HARBOR}corridor-identity-grouping-service:${CIGS_VERSION}
    container_name: sceg-cigs
    restart: unless-stopped
    ports:
      - "8096:80"
    environment:
      CORRIDOR_IDENTITY_GROUPING_SOURCE_GRAPHQL_HOST: sf-graphql-api
      CORRIDOR_IDENTITY_GROUPING_SOURCE_GRAPHQL_PORT: 80
      CORRIDOR_IDENTITY_GROUPING_STREAMS_APPLY_FOR_ALL_STREAMS: "true"
      CORRIDOR_IDENTITY_GROUPING_FACE_FILTER_REQUIRE_FACE_TEMPLATE: "true"
      CORRIDOR_IDENTITY_GROUPING_FACE_FILTER_FACE_SIZE_MIN: 15
      CORRIDOR_IDENTITY_GROUPING_FACE_FILTER_FACE_QUALITY_MIN: 100
      CORRIDOR_IDENTITY_GROUPING_FACE_FILTER_TEMPLATE_QUALITY_MIN: 50
      CORRIDOR_IDENTITY_GROUPING_FACE_FILTER_YAW_ANGLE_MIN: -50
      CORRIDOR_IDENTITY_GROUPING_FACE_FILTER_YAW_ANGLE_MAX: 50
      CORRIDOR_IDENTITY_GROUPING_FACE_FILTER_PITCH_ANGLE_MIN: -50
      CORRIDOR_IDENTITY_GROUPING_FACE_FILTER_PITCH_ANGLE_MAX: 50
      CORRIDOR_IDENTITY_GROUPING_FACE_FILTER_ROLL_ANGLE_MIN: -50
      CORRIDOR_IDENTITY_GROUPING_FACE_FILTER_ROLL_ANGLE_MAX: 50
    volumes:
      - ./secrets/iengine.lic:/etc/innovatrics/iengine.lic:ro

  frontend:
    image: ${FRONTEND_REGISTRY}biometriccorridor:${FRONTEND_VERSION}
    container_name: sceg-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8095}:80"
    environment:
      FOUNDATION_URL: http://sceg-hub:8090
      SMARTFACE_GQL_URL: http://SFGraphQLApi:80
      SMARTFACE_API_URL: http://SFApi:80

networks:
  default:
    name: sf-network
    external: true
